# Generated by Django 2.2.4 on 2019-09-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
