# Generated by Django 2.2.4 on 2019-09-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pronotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
